import '../../app/globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <div>
        {children}
    </div>
  )
}
